defmodule MyApp.Repo.Migrations.AddNicknameIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:rodents, [:nickname], name: "rodents_nickname_index")
  end

  def down do
    drop_if_exists unique_index(:rodents, [:nickname], name: "rodents_nickname_index")
  end
end