defmodule MyApp.Repo.Migrations.CreateBirdTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bird_to_tag, primary_key: false) do
      add :bird_id,
          references(:birds,
            column: :id,
            name: "bird_to_tag_bird_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          primary_key: true,
          null: false

      add :tag_id,
          references(:ashtag,
            column: :id,
            name: "bird_to_tag_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:bird_to_tag, "bird_to_tag_tag_id_fkey")

    drop constraint(:bird_to_tag, "bird_to_tag_bird_id_fkey")

    drop table(:bird_to_tag)
  end
end