defmodule MyApp.Repo.Migrations.CreateTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ashtag, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :slug, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:ashtag, [:slug], name: "ashtag_slug_index")
  end

  def down do
    drop_if_exists unique_index(:ashtag, [:slug], name: "ashtag_slug_index")

    drop table(:ashtag)
  end
end