defmodule MyApp.Repo.Migrations.CreateBirds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:birds, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :nickname, :text, null: false
      add :active, :boolean, null: false, default: false
      add :type, :text, default: "unknown"
      add :weight, :decimal
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:birds, [:nickname], name: "birds_nickname_index")
  end

  def down do
    drop_if_exists unique_index(:birds, [:nickname], name: "birds_nickname_index")

    drop table(:birds)
  end
end